name: Deploy feed

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: ".node-version"
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Generate feed
        run: pnpm run generate
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "feed"

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
