name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: ".node-version"
      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run generate
